### 192.168.99.100 - the default docker machine
GET http://192.168.99.100:24005/authorize?user=vadim&password=123456
Accept: application/json

###
POST http://192.168.99.100:24005/reg
Content-Type: application/json

{
  "name" : "vadim",
  "password" : "123456"
}

###

